### ISSUE TITLE
KeyError: 'server'

### ISSUE THREAD

**Issue by DarremMolko** [jorgeajimenezl/webdav-telegram#1]
Hola Jorge. Acabo de alojar este bot en Heroku pero me he encontrado con el siguiente error:

```
2022-05-17T16:38:57.371495+00:00 app[worker.1]: Task exception was never retrieved
2022-05-17T16:38:57.371524+00:00 app[worker.1]: future: <Task finished name='Task-655' coro=<FileModule.list() done, defined at /app/modules/file.py:38> exception=KeyError('server')>
2022-05-17T16:38:57.371524+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-17T16:38:57.371525+00:00 app[worker.1]:   File "/app/modules/file.py", line 41, in list
2022-05-17T16:38:57.371525+00:00 app[worker.1]:     ret = urlparse(data["server"])
2022-05-17T16:38:57.371526+00:00 app[worker.1]: KeyError: 'server'

```
El mismo ocurre al usar los comandos /list o /free (luego de ya haber configurado los datos de mi servidor con el comando/settings).

**Comment by DarremMolko** [comment]
Luego de realizar los cambios en el pr de JimScope en mi repositorio he logrado configurar mi servidor WebDav con éxito y acceder al mismo mediante el bot, pero me he encontrado con otro problema (adjunto captura):
![photo_2022-05-18](https://user-images.githubusercontent.com/70179709/169019932-6a5b7332-296c-472b-a4d1-18a6b9b6d13b.jpg)
No hubo error alguno en la consola de Heroku por lo que no puedo proporcionar logs.

**Comment by jorgeajimenezl** [comment]
Buenas @DarremMolko
Ahora pienso poner y cambiar algunas líneas para que proporcione un log y así poder ver el error, porque realmente me es difícil encontrarlo simplemente así, cuando haga el commit le digo para q haga deploy y me diga que error le muestra.

EDIT: Prueba con hacer deploy: [https://github.com/jorgeajimenezl/webdav-telegram/commit/f5164a7e21ebd5eb84d8a70febd717380098d6c9](https://github.com/jorgeajimenezl/webdav-telegram/commit/f5164a7e21ebd5eb84d8a70febd717380098d6c9)

**Comment by DarremMolko** [comment]
Aquí dejo lo que he podido encontrar con el último commit:

**ACCIÓN/COMANDO:** /list

![list](https://user-images.githubusercontent.com/70179709/169054882-4f396707-2147-459f-8ba2-d7a55ab1e3ff.jpg)

**LOGS:** Aún sin nada en la consola

**ACCIÓN/COMANDO:** Intento de subida de enlace directo

![uploadone](https://user-images.githubusercontent.com/70179709/169055658-0f30f373-c6cd-4ed8-be94-b8f02787c90c.jpg)
![uploadtwo](https://user-images.githubusercontent.com/70179709/169055715-912828e9-022d-4904-8b83-9a77838181cc.jpg)

**LOGS:**

```
2022-05-18T13:26:37.995834+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:26:40 UTC)" raised an exception
2022-05-18T13:26:37.995844+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:37.995845+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:37.995845+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:37.995846+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:37.995846+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:37.995847+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:37.995865+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:37.995866+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'
2022-05-18T13:26:40.995466+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:26:43 UTC)" raised an exception
2022-05-18T13:26:40.995475+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:40.995476+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:40.995477+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:40.995477+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:40.995478+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:40.995478+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:40.995479+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:40.995480+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'
2022-05-18T13:26:43.995124+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:26:46 UTC)" raised an exception
2022-05-18T13:26:43.995149+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:43.995159+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:43.995160+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:43.995160+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:43.995162+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:43.995163+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:43.995163+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:43.995164+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'
2022-05-18T13:26:46.995145+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:26:49 UTC)" raised an exception
2022-05-18T13:26:46.995153+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:46.995153+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:46.995154+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:46.995154+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:46.995154+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:46.995155+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:46.995155+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:46.995156+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'
2022-05-18T13:26:49.995784+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:26:52 UTC)" raised an exception
2022-05-18T13:26:49.995820+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:49.995822+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:49.995822+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:49.995822+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:49.995823+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:49.995823+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:49.995824+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:49.995825+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'
2022-05-18T13:26:52.994882+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:26:55 UTC)" raised an exception
2022-05-18T13:26:52.994907+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:52.994908+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:52.994909+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:52.994909+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:52.994910+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:52.994910+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:52.994911+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:52.994912+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'
2022-05-18T13:26:55.994830+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:26:58 UTC)" raised an exception
2022-05-18T13:26:55.994843+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:55.994844+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:55.994844+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:55.994845+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:55.994845+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:55.994846+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:55.994847+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:55.994847+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'
2022-05-18T13:26:58.994944+00:00 app[worker.1]: Job "WebdavModule._updater (trigger: interval[0:00:03], next run at: 2022-05-18 13:27:01 UTC)" raised an exception
2022-05-18T13:26:58.994953+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:26:58.994953+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2022-05-18T13:26:58.994954+00:00 app[worker.1]:     retval = await job.func(*job.args, **job.kwargs)
2022-05-18T13:26:58.994954+00:00 app[worker.1]:   File "/app/modules/webdav.py", line 172, in _updater
2022-05-18T13:26:58.994955+00:00 app[worker.1]:     text = f"{description} ({current_text} / {total_text})\nSpeed: {utils.get_str(naturalsize(speed, binary=True))}/sec\nETA: {utils.get_str(naturaldelta(eta))}"
2022-05-18T13:26:58.994955+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/humanize/filesize.py", line 52, in naturalsize
2022-05-18T13:26:58.994957+00:00 app[worker.1]:     bytes = float(value)
2022-05-18T13:26:58.994958+00:00 app[worker.1]: TypeError: float() argument must be a string or a number, not 'NoneType'

```

**ACCIÓN/COMANDO:** RENOMBRAR
**LOGS**: 

```
2022-05-18T13:16:04.112293+00:00 app[worker.1]: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:16:04.112311+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:16:04.112311+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
2022-05-18T13:16:04.112312+00:00 app[worker.1]:     if await handler.check(self.client, parsed_update):
2022-05-18T13:16:04.112327+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/handlers/handler.py", line 37, in check
2022-05-18T13:16:04.112327+00:00 app[worker.1]:     return await client.loop.run_in_executor(
2022-05-18T13:16:04.112328+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2022-05-18T13:16:04.112328+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2022-05-18T13:16:04.112328+00:00 app[worker.1]:   File "/app/button.py", line 79, in <lambda>
2022-05-18T13:16:04.112329+00:00 app[worker.1]:     lambda flt, _, query: query.data.startswith(flt.data), data=self.prefix
2022-05-18T13:16:04.112329+00:00 app[worker.1]: TypeError: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:16:04.112705+00:00 app[worker.1]: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:16:04.112705+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:16:04.112706+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
2022-05-18T13:16:04.112706+00:00 app[worker.1]:     if await handler.check(self.client, parsed_update):
2022-05-18T13:16:04.112706+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/handlers/handler.py", line 37, in check
2022-05-18T13:16:04.112706+00:00 app[worker.1]:     return await client.loop.run_in_executor(
2022-05-18T13:16:04.112707+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2022-05-18T13:16:04.112707+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2022-05-18T13:16:04.112707+00:00 app[worker.1]:   File "/app/button.py", line 79, in <lambda>
2022-05-18T13:16:04.112707+00:00 app[worker.1]:     lambda flt, _, query: query.data.startswith(flt.data), data=self.prefix
2022-05-18T13:16:04.112707+00:00 app[worker.1]: TypeError: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:16:04.113054+00:00 app[worker.1]: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:16:04.113054+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:16:04.113055+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
2022-05-18T13:16:04.113055+00:00 app[worker.1]:     if await handler.check(self.client, parsed_update):
2022-05-18T13:16:04.113055+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/handlers/handler.py", line 37, in check
2022-05-18T13:16:04.113055+00:00 app[worker.1]:     return await client.loop.run_in_executor(
2022-05-18T13:16:04.113055+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2022-05-18T13:16:04.113056+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2022-05-18T13:16:04.113056+00:00 app[worker.1]:   File "/app/button.py", line 79, in <lambda>
2022-05-18T13:16:04.113056+00:00 app[worker.1]:     lambda flt, _, query: query.data.startswith(flt.data), data=self.prefix
2022-05-18T13:16:04.113056+00:00 app[worker.1]: TypeError: startswith first arg must be str or a tuple of str, not bytes

```

**ACCIÓN/COMANDO:** DESCARGAR
**LOGS**: 

```
2022-05-18T13:23:51.756252+00:00 app[worker.1]: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:23:51.756275+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:23:51.756276+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
2022-05-18T13:23:51.756277+00:00 app[worker.1]:     if await handler.check(self.client, parsed_update):
2022-05-18T13:23:51.756278+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/handlers/handler.py", line 37, in check
2022-05-18T13:23:51.756278+00:00 app[worker.1]:     return await client.loop.run_in_executor(
2022-05-18T13:23:51.756694+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2022-05-18T13:23:51.756694+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2022-05-18T13:23:51.756694+00:00 app[worker.1]:   File "/app/button.py", line 79, in <lambda>
2022-05-18T13:23:51.756694+00:00 app[worker.1]:     lambda flt, _, query: query.data.startswith(flt.data), data=self.prefix
2022-05-18T13:23:51.756695+00:00 app[worker.1]: TypeError: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:23:51.756700+00:00 app[worker.1]: startswith first arg must be str or a tuple of str, not bytes
2022-05-18T13:23:51.756700+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-18T13:23:51.756701+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
2022-05-18T13:23:51.756701+00:00 app[worker.1]:     if await handler.check(self.client, parsed_update):
2022-05-18T13:23:51.756701+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/handlers/handler.py", line 37, in check
2022-05-18T13:23:51.756701+00:00 app[worker.1]:     return await client.loop.run_in_executor(
2022-05-18T13:23:51.756702+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
2022-05-18T13:23:51.756702+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2022-05-18T13:23:51.756702+00:00 app[worker.1]:   File "/app/button.py", line 79, in <lambda>
2022-05-18T13:23:51.756703+00:00 app[worker.1]:     lambda flt, _, query: query.data.startswith(flt.data), data=self.prefix
2022-05-18T13:23:51.756703+00:00 app[worker.1]: TypeError: startswith first arg must be str or a tuple of str, not bytes

```

**Comment by jorgeajimenezl** [comment]
@DarremMolko  This bug has been fixed, sorry for forgetting to mention it
